name: build to github pages

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          mkdir build
          quarto render index.qmd --output-dir build
      
      steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
         with:
            r-version: '4.1.1'
        - run: Rscript -e 'print("hello")'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          clean: true
